### PR TITLE
Support latest coverage 40x

### PR DESCRIPTION
**Pull request by ahxxm**
Main work is done by [rdegges](https://github.com/z4r/python-coveralls/pull/41).

Test failure will be fixed when merged, it is caused by this line in `coveralls/repository.py`:

    branch = os.environ.get('CIRCLE_BRANCH') or os.environ.get('TRAVIS_BRANCH', sh.git('rev-parse', '--abbrev-ref', 'HEAD').strip())

`TRAVIS_BRANCH` overwrites result from git command. Not sure what to do with it.

### CODE REVIEW

**Comment by ahxxm** [comment]
hmm. works fine.

**Comment by ahxxm** [comment]
@z4r would you please also update dist version on pypi?  :)

**Comment by z4r** [comment]
Hi @ahxxm, python-coveralls 2.6.0 is online now :)

**Comment by ahxxm** [comment]
thank you!

**Pull request merged**
